---
- name: nginx-role
  src: https://github.com/sisipka/nginx-role
  scm: git
  version: 0.0.1
- name: lighthouse-role
  src: https://github.com/sisipka/lighthouse-role
  scm: git
  version: 0.0.3
- name: vector-role
  src: https://github.com/sisipka/vector-role
  scm: git
  version: 0.0.4
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  name: clickhouse
  scm: git
  version: "1.11.0"
   